# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic


class Window(QtWidgets.QMainWindow):
    def __init__(self):
        super(Window, self).__init__()

        uic.loadUi("transcribe_ui.ui",self)

        self.pushButton = self.findChild(QtWidgets.QPushButton, "pushButton")
        self.label = self.findChild(QtWidgets.QLabel, "label")

        self.pushButton.clicked.connect(self.clicked)

        self.show()

    def clicked(self):
        #self.label.setText("YOO!!!")
        fname = QtWidgets.QFileDialog.getOpenFileName(self, "Open File", "", "All Files (*)")
        print(fname[0])
        self.label.setText(str(fname))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UIWindow = Window()
    sys.exit(app.exec_())
